work_dir: analysis_large
sequences: /data/analyses/gisaid/sequences.fasta #/home/user1/run1/gisaid/sequences1010.fasta
meta: /data/analyses/gisaid/metadata.csv
datasets_dir: datasets
antibody_contacts_data: datasets/antibodies/contacts-variable-probe_v2/probe-13/contacts-..tab 
lineages: "B.1 B.1.1 D.2 B.1.2 B.1.177 B.1.1.7 AY.4 B.1.617.2 AY.43 BA.1.1 BA.2 BA.2.12.1 BA.5.2.1 BA.5.2 BQ.1.1 AY.4.5 Q.1 B.1.177.60 BA.2.9" # most abundant each quarter worldwide more than  1000
# lineages: "AY.4.5	Q.1	B.1.1.7	B.1.177.60	BA.2	BA.2.9" #- LT most abundant
reference_id: 'MN908947 (Wuhan-Hu-1/2019)'
reference_lineage: "BA.2"
cleanup_keep_fraction_of_columns: 0.80
cleanup_remove_proc_mostN_having: 20
target_amount: 12000
subset_amount_maximum: 30
maximum_amount_4_splits: 2000
reference: datasets/NC_045512.gb
